default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
        args: ['--unsafe']
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: ['--branch', 'main']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.394
    hooks:
      - id: pyright
        stages: [pre-push]
  - repo: local
    hooks:
      - id: check-git-author
        name: check git author is not noreply
        entry: scripts/check-git-author.sh
        language: script
        stages: [pre-commit]
        always_run: true
        pass_filenames: false
