name: 'Setup Python with uv'
description: 'Setup Python with uv'
inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.10'
  install-dependencies:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: 'Install uv'
      uses: astral-sh/setup-uv@v5
    - name: 'Setup Python'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      shell: bash
      run: uv sync
